spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Install/h2/localdb/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        sout 표시되지 않도록 주석처리
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace